package com.example.naroo.betaops.domain

enum class BetaEventType {
    AUTH_LOGIN_SUCCEEDED,
    DIAGNOSTIC_STARTING_POINT_SELECTED,
    DIAGNOSTIC_SESSION_CREATED,
    DIAGNOSTIC_QUESTION_SHOWN,
    DIAGNOSTIC_ANSWER_SELECTED,
    DIAGNOSTIC_SESSION_ABANDONED,
    DIAGNOSTIC_ANSWERS_SUBMITTED,
    RECOVERY_MISSION_CREATED,
    RECOVERY_MISSION_SUBMITTED,
}
