package com.example.naroo.auth.adapter.`in`.web.errorCode

import com.example.naroo.infrastructure.web.ErrorCode

enum class AuthErrorCode(
    override val value: String,
) : ErrorCode {
    LOGIN_ID_ALREADY_EXISTS("AUTH_LOGIN_ID_ALREADY_EXISTS"),
    EMAIL_ALREADY_EXISTS("AUTH_EMAIL_ALREADY_EXISTS"),
    INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    INVALID_REFRESH_TOKEN("AUTH_INVALID_REFRESH_TOKEN"),
    INVALID_EMAIL_VERIFICATION_TOKEN("AUTH_INVALID_EMAIL_VERIFICATION_TOKEN"),
    REFRESH_TOKEN_REQUIRED("AUTH_REFRESH_TOKEN_REQUIRED"),
    UNAUTHORIZED("AUTH_UNAUTHORIZED"),
}
